import { ElementRef, EventEmitter } from '@angular/core';
import { InputBase } from '../../core/components/input/input';
export declare class MbscInput extends InputBase {
    vInput: ElementRef;
    accept: string;
    autocapitalize: string;
    autocomplete: 'on' | 'off';
    autocorrect: string;
    autofocus: string;
    disabled: boolean;
    dropdown: boolean;
    endIcon: string;
    endIconSrc: string;
    endIconSvg: string;
    error: boolean;
    errorMessage: string;
    hideIcon: string;
    hideIconSvg: string;
    id: string;
    inputClass: string;
    inputStyle: 'underline' | 'box' | 'outline';
    label: string;
    labelStyle: 'stacked' | 'inline' | 'floating';
    max: number;
    maxlength: number;
    min: number;
    minlength: number;
    multiple: string;
    name: string;
    passwordToggle: boolean;
    pattern: string;
    pickerMap: any;
    pickerValue: any;
    placeholder: string;
    readonly: boolean;
    required: string;
    ripple: boolean;
    rows: number;
    showIcon: string;
    showIconSvg: string;
    spellcheck: string;
    startIcon: string;
    startIconSrc: string;
    startIconSvg: string;
    step: number;
    tags: boolean;
    type: string;
    value: any;
    onChange: EventEmitter<any>;
    _id: string;
    _triggerEvent(ev: any): void;
    protected _onValueChange(): void;
    protected _mounted(): void;
}
